### ISSUE TITLE
Trying to mock multiple functions with the is_not_null constraint does not work

### ISSUE THREAD

**Issue by a-cristi** [cgreen-devs/cgreen#235]
I'm using Ubuntu 20.04 with GCC 9.3.0-10ubuntu2 and clang 10.0.0-4ubuntu1 (the issue can be reproduced with both compilers), with cgreen compiled from source from commit `34cd1b6 - Extract common "discover_tests" function` from the master branch. 

The problem is that setting two different `is_not_null` constraints for different functions makes cgreen think that both functions should define that particular parameter. For lack of a better description I have a minimal sample with which I can reproduce this:

```
#include <cgreen/cgreen.h>
#include <cgreen/mocks.h>

Describe(test);
BeforeEach(test) {}
AfterEach(test) {}

void first_mock(int a, int *a_out)
{
    mock(a, a_out);
}

void second_mock(int b, int *b_out)
{
    mock(b, b_out);
}

int tested_func(int a, int b)
{
    int a_out, b_out;
    first_mock(a, &a_out); 
    second_mock(b, &b_out);
    return a_out + b_out;
}

Ensure(test, does_the_thing)
{
    int a_out_val = 10;
    int b_out_val = 20;

    expect(first_mock, 
        when(a_out, is_not_null),
        will_set_contents_of_parameter(a_out, &a_out_val, sizeof(a_out_val)));
    expect(second_mock, 
        when(b_out, is_not_null),
        will_set_contents_of_parameter(b_out, &b_out_val, sizeof(b_out_val)));

    assert_that(tested_func(1, 2), is_equal_to(30));
}

int main(void)
{
    TestSuite *suite = create_test_suite();
    add_test_with_context(suite, test, does_the_thing);
    return run_test_suite(suite, create_text_reporter());
}
```

Compiled with:

```
gcc test.c /usr/local/lib/libcgreen.so -o test
```

When run this gives the following output:

```
$ ./test
Running "main" (1 test)...
test.c:31: Failure: does_the_thing
        Mocked function [first_mock] did not define a parameter named [b_out]. Did you misspell it in the expectation or forget it in the mock's argument list?

test.c:38: Failure: does_the_thing
        Expected [tested_func(1, 2)] to [equal] [30]
                actual value:                   [262849778]
                expected value:                 [30]

  "main": 1 pass, 2 failures in 1ms.
Completed "main": 1 pass, 2 failures in 1ms.
```

If I remove `when(a_out, is_not_null)` or `when(b_out, is_not_null),`, or if I rename the parameter to have the same name in both cases it seems to work as intended:

```
$ ./test
Running "main" (1 test)...
  "main": 2 passes in 0ms.
```

**Comment by thoni56** [comment]
Thanks for the report with a good example.

A work-around seems to be to use `when(b_out, is_not_equal_to(NULL))`;

I'll look into it.

**Comment by ianichitei** [comment]
Thank you. `when(..., is_not_equal_to(NULL))` works.

**Comment by a-cristi** [comment]
> Thanks for the report with a good example.
> 
> A work-around seems to be to use `when(..., is_not_equal_to(NULL))`;
> 
> I'll look into it.

Thank you. `when(..., is_not_equal_to(NULL))` works.

**Comment by thoni56** [comment]
This is caused by the "optimized" implementation of `is_not_null` to use a singleton static constraint data structure. (And it has been that way for years ;-)

But as often is the case, premature optimization is the root of all evil. Those singletons are used to hold the parameter name, so if you use it more than once in a test the parameter name will be overwritten, and the last one will be kept.

I'm working on a fix for this. It will be source level compatible, but not library version compatible. So, I haven't decided if this warrants a new release yet.

**Comment by a-cristi** [comment]
> This is caused by the "optimized" implementation of `is_not_null` to use a singleton static constraint data structure. (And it has been that way for years ;-)

I'm guessing that this also affects `is_null`, `is_true`, and `is_false`, and `is_true`, all of which I can replace with `is_equal_to`/`is_not_equal_to`.

Thank you again for your quick response.

**Comment by matthargett** [comment]
Thanks for reporting the problem and to @thoni56 for fixing it. Not sure what we (I) were thinking here, sorry for the inconvenience! It's so cool to see the project continue to get new users 10 years after I originally contributed and deployed it at several companies.

**Comment by thoni56** [comment]
Thanks, @matthargett! Nice to see that you are still keeping an eye on this project.

**Comment by a-cristi** [comment]
> Thanks for reporting the problem and to @thoni56 for fixing it. Not sure what we (I) were thinking here, sorry for the inconvenience! It's so cool to see the project continue to get new users 10 years after I originally contributed and deployed it at several companies.

I am looking for a testing and mocking framework for C, to introduce some unit tests for a code base that lacks them, and so far cgreen is my favorite (I think that the docs are great, the mocking is really powerful, and a bug I found was fixed really fast). So thank you for what looks like a really cool and easy to use testing framework.

**Comment by thoni56** [comment]
Thank you! Will be happy to work with you to support successful use of Cgreen!

I'm on a similar quest with some really legacy project and would be happy to share any experiences. Specifically I'm interested in what where the stumbling stones related to introducing unit tests. Perhaps there are some patterns that we could use in the documentation to help others.

**Comment by a-cristi** [comment]
> I'm on a similar quest with some really legacy project and would be happy to share any experiences. Specifically I'm interested in what where the stumbling stones related to introducing unit tests. Perhaps there are some patterns that we could use in the documentation to help others.

This is a project with a somewhat long life span, and still under active development, so some parts of it are old, while others are new and shiny. So far it relied on all kinds of tests, except unit testing, but the lack of unit tests is something that I feel like we need to address. 

We settled on the idea that unit testing is hard in C and especially hard in our case, so we haven't really invested a lot of energy into this. We tried some things in the past, but we ended up building some really complex systems around the project that were fun to work on at first, but in some regards were more complex than some parts of the project and as a result were hard to maintain and no one ended up using them. 

Lately I've been looking for frameworks that can make things simple, so that people will want to use them. I'm currently at the stage where I'm preparing my final notes in order to present them to the team. So the first challenge is not a technical one: how do we convince ourselves that the way we do things now can be improved and how do we make that change? As always, changing the processes a team has used for a long time is harder than changing the code.

Following that, how do we choose the first things we want to test? Ideally, the first targets should be simple enough that we don't get stuck trying to do something we are not prepared for, but also important enough to make people feel like they are contributing something of value, and not just checking a box on a todo list. How do you go from not writing tests to writing meaningful tests?

I hope to start working on the technical challenges in the following weeks.

**Comment by thoni56** [comment]
Interesting. I'd be interested to hear how that goes.

I think you have to make things easy and ease your team into that "new" way of working.

Often when I  (or a team I coach) get started on an old project, I try to add a single, simple test somewhere. Focus on what's possible and simple rather than where the need is largest. That get's me and my team into a sense of that it is possible, if only with limited value (at this point). With that approach we can think of "going for unittests" as an experiment where we can learn what's possible and comfortable. And even scrap it if we feel it will not work, after having tried for a while.

I'm not a strong believer in setting up "rules" up-front, like "DoD says unittests".  So I would not go for a hard rule until the whole team has evolved a knowledge and confidence that it will work. Until then I would work on the "culture" and small steps.

In my curerntly most active private project, a C refactoring browser originally built around 2000 and left for dead in 2009 (https://github.com/thoni56/c-xrefactory), there where no tests at all. Now I'm at ~63% coverage, but with only below 10% unit tests, and simple ones at that. Retro-fitting unittests is hard, so in the beginning, learning is the important part, so pretty much anything goes, and I try to add unittests whenever I rewrite a function, module or convert a macro into a function.

Later you can re-focus from functions as the SUT and going for "behavioural" unittests that tests interactions.

**Comment by a-cristi** [comment]
> I try to add a single, simple test somewhere. Focus on what's possible and simple rather than where the need is largest. That get's me and my team into a sense of that it is possible, if only with limited value (at this point). With that approach we can think of "going for unittests" as an experiment where we can learn what's possible and comfortable. And even scrap it if we feel it will not work, after having tried for a while.

This was my approach so far. I picked a small module and wrote a few tests, from really simple tests, to more complex ones, showing how things can be tackled. I'm especially happy that I managed to use the mocking functionality in cgreen (plus some help from the linker) to easily do some things for which we previously wrote a lot of complex code. It will be easier to start a discussion if I have some sample code that is actually doing something. I'll also be able to talk from experience (even if not a lot of experience), telling people what I liked, what was hard for me to understand, etc.

> I'm not a strong believer in setting up "rules" up-front, like "DoD says unittests". So I would not go for a hard rule until the whole team has evolved a knowledge and confidence that it will work. 

I totally agree. If you're setting up rules from the start people will either disregard them, do the bare minimum to be able to say "I did everything that was needed", and in the end everyone will be frustrated and we will achieve nothing. I want to gather everyone and to make a decision as a team that we will try to improve some of the things we've been complaining about for a long time (for example, there are some functions that people don't want to touch because there are no tests to warn them if they break something). This is how I was able to introduce or change other processes we were using in the past: showing, not telling.

> Retro-fitting unittests is hard, so in the beginning, learning is the important part, so pretty much anything goes, and I try to add unittests whenever I rewrite a function, module or convert a macro into a function.

This is a really good suggestion. We are pretty busy working on new features and improvements, so encouraging people to add tests early for new functionality could work. 

The project is closed source, so it is a bit hard to talk about it at the moment, but every feature has some associated tests that exercise all the parts involved in that feature, but some bugs are hard to trigger in this way and may depend on external conditions that are really hard to control, and with some focused unit tests that can be achieved without much effort. And the team already agrees with this. We sometimes fix a hard to reproduce bug just for it to resurface after a while and remain hidden for a long time just because it is hard to trigger and there is no way to reliably do regression testing. We may never have unit tests for some parts of the code base, but if we can isolate some functionality and easily simulate some external conditions that triggered a bug in the past and make it easy to check that it no longer happens I will be happy.

**Comment by dmeehan1968** [comment]
Request to re-open.  This breaks builds on XCode 12.0.0 (possibly 11.3 also) with the following link failures.

I'm creating a dynamic library containing my tests which I'm passing to cgreen-runner, the dylib is linked to the cgreen library (cgreen.1.3.0.dylib in green/build/src).

I've checked that the prior commit works, this commit and current master head fails the same.  

I've cleaned by green build directory and that of the project.   

I've run `git clean -dfX` to make sure that cgreen is cleared down correctly (also needed this as I was upgrading to Xcode 12 and pulled the latest from cgreen master at the same time, which picked up this change).

For now I should be able to revert back to my previous cgreen commit and not worry about the recent updates.

```
Undefined symbols for architecture x86_64:
  "_create_is_null_constraint", referenced from:
      [redacted source objects]
      ...
  "_create_is_true_constraint", referenced from:
      [redacted source objects]
      ...
  "_create_not_null_constraint", referenced from:
      [redacted source objects]
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by thoni56** [comment]
Hi @dmeehan1968!

To me it sounds like you are, despite everything, linking with an older version of the library. Exactly those missing functions are what's different from a 1.3.0 library and one built from HEAD. Are you sure your links are not picking up some other version? `/usr/local/lib` perhaps?

I'm building `Cgreen` itself using Apples `Apple clang version 12.0.0 (clang-1200.0.32.2)` which works.

**Comment by dmeehan1968** [comment]
Thanks, yes that was the problem, I had 1.2.0 libs and tools installed in /usr/local, I thought I was working from the project local versions, which had been my intention.

Works as expected on master.

Cheers
Dave

**Comment by thoni56** [comment]
Thanks for confirming! And thanks for using Cgreen!
